type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/atomic-studio-org/studio-presets/repo/fedora-%OS_VERSION%/atomic-studio-org-studio-presets-fedora-%OS_VERSION%.repo
remove:
  - plasma-welcome
install:
  - studio-presets-plasma
  - qpwgraph
  - materia-kde 
  - kde-connect
  - kwin-x11
  - plasma-workspace-x11 
