#!/usr/bin/env bash 
unload() {
    SINKID=$(LANG=C.UTF-8 pactl list | grep -B 1 "Name: module-jack-sink" | grep Module | sed 's/[^0-9]//g')
    SOURCEID=$(LANG=C.UTF-8 pactl list | grep -B 1 "Name: module-jack-source" | grep Module | sed 's/[^0-9]//g')
    pactl unload-module "$SINKID"
    pactl unload-module "$SOURCEID"
    sleep 5
    pacmd suspend false
}

trap unload EXIT

pacmd suspend true
jackd -r -dalsa -dhw:0 -r48000 -p1024 -n2 &
sleep 3
pactl load-module module-jack-sink channels=2
pactl load-module module-jack-source channels=2
pacmd set-default-sink jack_out
pacmd set-default-source jack_in
