name: universal-studio-gnome-nvidia
description: Operating system based on Fedora Atomic meant for content creators and artists

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - from-file: ./apps.yml
  - from-file: ./shared-sys.yml
  - from-file: ./apps-gnome.yml