# image will be published to ghcr.io/<user>/<name>
name: universal-studio
# description will be included in the image's metadata
description: Operating system based on Fedora Silverblue meant for artists

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: ./apps.yml
