name: atomic-studio-gnome-nvidia
description: Operating system based on Fedora Atomic meant for content creators and artists

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - from-file: common/shared-apps.yml
  - from-file: common/shared-files.yml
  - from-file: common/gnome-apps.yml
  - from-file: common/gnome-files.yml
  - type: yafti
  - type: signing