name: universal-studio-gnome
description: Operating system based on Fedora Atomic meant for content creators and artists

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - from-file: ./apps.yml
  - from-file: ./shared-sys.yml
  - from-file: ./apps-gnome.yml
