---
- type: files
  files:
    - usr: /usr

- type: rpm-ostree
  install:
    - qpwgraph
    - krita
    - blender
    - inkscape
    - ffmpeg
    - ardour8
    - audacity
    - qtractor
    - hydrogen
    - yoshimi
    - rakarrack
    - supercollider
    - csound
    - kdenlive
  remove:
    - firefox
    - firefox-langpacks

- type: default-flatpaks
  notify: true
  system:
    install:
      - org.mozilla.firefox
      - com.obsproject.Studio.Plugin.OBSVkCapture
      - org.freedesktop.Platform.VulkanLayer.OBSVkCapture
      - com.obsproject.Studio
      - org.gimp.GIMP
      - org.gimp.GIMP.Plugin.BIMP
      - org.gimp.GIMP.Plugin.Fourier
      - org.gimp.GIMP.Plugin.Lensfun
      - org.gimp.GIMP.Plugin.LiquidRescale
      - org.kde.digikam
      - com.github.qarmin.czkawka
      - org.darktable.Darktable

- type: signing
