type: rpm-ostree
install:
  - papirus-icon-theme
  - materia-gtk-theme
  - krita
  - blender
  - inkscape
  - ffmpeg
  - audacity
  - yoshimi
  - rakarrack
  - supercollider
  - csound
  - guitarix
  - ladspa
  - ladspa-guitarix-plugins
  - ardour8
  - kdenlive
remove:
  - firefox
  - firefox-langpacks
