type: rpm-ostree
install:
  - papirus-icon-theme
  - materia-gtk-theme
  - krita
  - blender
  - inkscape
  - ffmpeg
  - audacity
  - yoshimi
  - rakarrack
  - supercollider
  - csound
  - guitarix
  - ladspa
  - ladspa-guitarix-plugins
  - ardour8
  - kdenlive
  - zita-at1
  - zita-rev1
  - rosegarden4
  - entangle
  - ffado
  - fluidsynth
  - csound-fluidsynth
  - hugin
  - ImageMagick
  - jack-mixer
  - jack-keyboard
  - k3b
  - libreoffice
  - libreoffice-icon-theme-papirus
  - lmms
  - menulibre
  - musescore
  - mypaint
  - mudita24
  - meterbridge
  - phasex
  - pavucontrol
  - vlc
  - qsynth
  - qtractor
  - raysession
  - synfig
remove:
  - firefox
  - firefox-langpacks
