name: atomic-studio-nvidia-jack
description: Operating system based on Fedora Atomic meant for content creators and artists

base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest

modules:
  - from-file: common/shared/gui-apps.yml
  - from-file: common/shared/packages.yml
  - from-file: common/shared/nvidia/scripts.yml
  - from-file: common/shared/files.yml
  - from-file: common/shared/scripts.yml
  - from-file: common/shared/bling.yml
  - from-file: common/plasma/apps.yml
  - from-file: common/plasma/files.yml
  - from-file: common/audio/audinux.yml
  - from-file: common/audio/jack-packages.yml
  - from-file: common/audio/jack-services.yml
  - type: yafti
  - type: signing
