type: rpm-ostree
install:
  - fira-code-fonts
  - papirus-icon-theme
  - materia-gtk-theme
  - librecad
  - krita
  - blender
  - inkscape
  - audacity
  - yoshimi
  - rakarrack
  - supercollider
  - csound
  - guitarix
  - ladspa
  - ladspa-guitarix-plugins
  - ardour8
  - kdenlive
  - zita-at1
  - zita-rev1
  - rosegarden4
  - entangle
  - ffado
  - fluidsynth
  - csound-fluidsynth
  - hugin
  - ImageMagick
  - jack-mixer
  - jack-keyboard
  - k3b
  - libreoffice
  - libreoffice-icon-theme-papirus
  - lmms
  - menulibre
  - musescore
  - mypaint
  - mudita24
  - meterbridge
  - phasex
  - pavucontrol
  - vlc
  - qsynth
  - qtractor
  - raysession
  - synfig
  - Carla
  - OpenLP
  - ddccontrol
  - jconvolver
  - jaaa
  - jacktrip
  - zynaddsubfx
  - obs-studio
  - obs-studio-plugin-vkcapture
  - obs-studio-plugin-webkitgtk
  - lsp-plugins
  - lsp-plugins-jack
  - lsp-plugins-lv2
  - calf
  - lv2-x42-plugins
  - lv2
  - lv2-carla
  - lv2-calf-plugins
  - sooperlooper
  - jack_capture
  - tuxguitar
  - amsynth 
  - vkeybd
  - gimp
  - gimp-fourier-plugin
  - gimp-jxl-plugin
  - gimp-lqr-plugin
  - gimp-paint-studio
  - gmic-gimp
  - gimp-save-for-web
  - gimp-lensfun
  - scribus
  - openshot
  - furnace
