type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/ycollet/audinux/repo/fedora-%OS_VERSION%/ycollet-audinux-fedora-%OS_VERSION%.repo
install:
  - aeolus
  - xtuner
  - jamin
  - DISTRHO-Ports
