type: rpm-ostree
install:
  - jack-audio-connection-kit
  - jack-audio-connection-kit-dbus
  - csound-jack
  - qemu-audio-jack
remove:
  - pipewire
  - pipewire-utils
  - pipewire-pulseaudio
  - pipewire-jack-audio-connection-kit
  - vlc-plugin-pipewire
