type: rpm-ostree
install:
  - jack-audio-connection-kit
  - jack-audio-connection-kit-dbus
  - csound-jack
  - qemu-audio-jack
  - qemu-audio-pa
  - pulseaudio
  - pulseaudio-utils
  - pulseaudio-module-jack
  - pulseaudio-module-bluetooth
  - pulseaudio-libs
remove:
  - pipewire-utils
  - pipewire-pulseaudio
  - pipewire-jack-audio-connection-kit
  - pipewire-jack-audio-connection-kit-libs
  - pipewire-codec-aptx
  - vlc-plugin-pipewire
