type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/patrickl/pipewire-wineasio/repo/fedora-%OS_VERSION%/patrickl-pipewire-wineasio-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/patrickl/yabridge/repo/fedora-%OS_VERSION%/patrickl-yabridge-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/patrickl/wine-tkg/repo/fedora-%OS_VERSION%/patrickl-wine-tkg-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/patrickl/wine-mono/repo/fedora-%OS_VERSION%/patrickl-wine-mono-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/patrickl/vkd3d/repo/fedora-%OS_VERSION%/patrickl-vkd3d-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/patrickl/wine-dxvk/repo/fedora-%OS_VERSION%/patrickl-wine-dxvk-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/patrickl/winetricks/repo/fedora-%OS_VERSION%/patrickl-winetricks-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/patrickl/libcurl-gnutls/repo/fedora-%OS_VERSION%/patrickl-libcurl-gnutls-fedora-%OS_VERSION%.repo
install:
  - pipewire-wineasio
  - yabridge
  - wine
  - wine-mono
  - mingw32-wine-gecko
  - mingw64-wine-gecko
  - wine-dxvk
  - winetricks
  - yabridge 
  - libcurl-gnutls
  - icoutils
  - perl-Image-ExifTool
