name: atomic-studio-gnome
description: Operating system based on Fedora Atomic meant for content creators and artists

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - from-file: common/shared/apps.yml
  - from-file: common/shared/files.yml
  - from-file: common/shared/scripts.yml
  - from-file: common/gnome/scripts.yml
  - from-file: common/gnome/apps.yml
  - from-file: common/gnome/files.yml
  - from-file: common/audio/pipewire-flatpaks.yml
  - from-file: common/audio/pipewire-services.yml
  - from-file: common/audio/audinux.yml
  - type: yafti
  - type: signing
