name: Auto Assign
on:
  issues:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: First interaction
      uses: actions/first-interaction@v1.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: tulilirockz
          numOfAssignee: 1
    - name: Add to Project Tracking
      uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/orgs/atomic-studio-org/projects/3
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Summary Issues
      uses: sourcegraph/summary-issues@v1.2.1
