name: Build Atomic Studio ISOs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-iso.yml'

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-iso:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    container:
      image: fedora:${{ matrix.major_version }}
      options: "--privileged"
      volumes:
        - "/:/host"
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: atomic-studio
            variant: Kinoite
          - name: atomic-studio-hardened
            variant: Kinoite
          - name: atomic-studio-nvidia
            variant: Kinoite
          - name: atomic-studio-nvidia-hardened
            variant: Kinoite
          - name: atomic-studio-gnome
            variant: Silverblue
          - name: atomic-studio-gnome-nvidia
            variant: Silverblue
          - name: atomic-studio-gnome-hardened
            variant: Silverblue
          - name: atomic-studio-gnome-nvidia-hardened
            variant: Silverblue
        major_version: [39]
        image_tag: [latest]
    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v6
        with:
          remove-codeql: 'true'

      - name: Build ISOs
        uses: ublue-os/isogenerator@1.0.9
        id: build
        with:
          ARCH: x86_64
          IMAGE_NAME: ${{ matrix.image_name }}
          IMAGE_REPO: ghcr.io/atomic-studio-org
          VARIANT: ${{ matrix.image.variant }} 
          VERSION: ${{ matrix.major_version }}
          IMAGE_TAG: ${{ matrix.image_tag }}
          SECURE_BOOT_KEY_URL: 'https://github.com/ublue-os/akmods/raw/main/certs/public_key.der'
          ENROLLMENT_PASSWORD: 'ublue-os'

      - name: Upload ISOs and Checksum to Job Artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image_name }}-${{ matrix.image_tag }}-${{ matrix.major_version}}
          path: ${{ steps.build.outputs.output-directory }}
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
